#!/usr/bin/env bash

# Install pip & dependencies

echo "Installing pip..."
python3 -m ensurepip

if [ $? -eq 0 ] ; then
    echo "Success: pip OK, installing dependencies..."
    yes | python3 -m pip install -r requirements.txt --quiet
    if [ $? -eq 0 ]; then
        echo "Success: dependencies have been installed."
    else
        echo "Error: dependencies could not be installed."
        exit 1
    fi
else
    echo "Error: pip could not be installed."
    exit 1
fi
