#!/usr/bin/env bash

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $SCRIPTPATH

./update
./install

if [ $? -eq 0 ] ; then
    echo "Success: dependencies OK, checking for obligatory files..."
else
    echo "Error: dependencies could not be installed."
    exit 1
fi

if [ -e ./.env ] && [ -e oauth2.json ] &&  [ -e config.yml ] ; then
    echo "Success: .env, oauth2.json and config.yml files found, running the bot..."
    python3 -OO -m redesc.app
else
    echo "Error: one of (1) .env, (2) oauth2.json and (3) config.yml files is missing, aborting..."
    exit 1
fi
